export const GroupConstants = {
  INIT_GROUP: 'INIT_GROUP',
  SET_GROUP: 'SET_GROUP',
  SET_GROUPS: 'SET_GROUPS',
  UNSET_GROUP: 'UNSET_GROUP',
  UPDATE_GROUPS: 'UPDATE_GROUPS',
  SET_ACTIVE: 'SET_ACTIVE',
  LEAVE_GROUP: 'LEAVE_GROUP',
  JOIN_GROUP: 'JOIN_GROUP'
};