export const UserConstants = {
  
  INIT_USER: 'INIT_USER',
  SET_USER: 'SET_USER',
  UNSET_USER: 'UNSET_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  CREATE_USER: 'CREATE_USER',
  ADD_FAVORITE: 'ADD_FAVORITE',
  REMOVE_FAVORITE: 'REMOVE_FAVORITE',
  EDIT_FAVORITE: 'EDIT_FAVORITE'

};